view scores submition by class:
a table showing scores submition
S/N  |  SUBJECT  |  TEACHER  |  CLASS   | TOTAL STUDENTS  | PROGRSS |  ACTION (VIEW,NOTIFY TEACHER,DELETE)
VIEW: TO VIEW THE FULL SCORESHEET
DELETE: TO DELETE SCORES ENTRY
NOTIFY TEACHER: TO SEND MESSAGE TO THE SUBJET TEACHER 

AND A BUTTON AT THE TOP BEFORE THE TABLE TO ON/OFF SCORES ENTRY
IF ON TEACHERS CAN ENTER THEIR SCORES AND IF OFF TEACHERS CAN NOT ENTER SCORES
